name: Morea CORE (Change me)
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
safe: false
baseurl: /core
exclude: [morea]
morea_theme: spacelab
morea_navbar_items:
  #- Prerequisites
  - Modules
  - Outcomes
  - Readings
  - Experiences
  - Assessments
  #-Schedule

# The following properties are optional.
# See the User Guide (http://morea-framework.github.io/userguide.html) for more info.

# morea_course: ics311
# morea_domain: http://morea-framework.github.io/
# morea_google_analytics_tracking_id: "<your tracking id here>"